name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Build Win x86
        run: GOOS=windows GOARCH=386 CGO_ENABLED=0 go build -ldflags '-s -w' -trimpath -o './dist/florida-men-win.exe' florida-men.go
      - name: Build Mac amd64
        run: GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-s -w' -trimpath -o './dist/florida-men-darwin-amd64' florida-men.go
      - name: Build Mac arm64
        run: GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags '-s -w' -trimpath -o './dist/florida-men-darwin-arm64' florida-men.go
      - name: Build Linux amd64
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-s -w' -trimpath -o './dist/florida-men-linux-amd64' florida-men.go
      
# currently disabled cause of personal github rate limits (storage)
#      - uses: actions/upload-artifact@v3
#        with:
#            name: florida-men
#            path: dist/florida-men
#            if-no-files-found: error