name: Test

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

    ### tests ###
      - name: Test
        run: go test -v ./...

    ### linting ###
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --fast=false --sort-results --max-same-issues=0